### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by hunkardoner** [ikascom/create-ikas-theme#1]
apple@APPLE-MacBook-Pro first-theme % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ikas-theme@0.0.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0 || ^17.0.0 || ^18.0.0" from @stripe/react-stripe-js@1.14.1
npm ERR!   node_modules/@stripe/react-stripe-js
npm ERR!     peer @stripe/react-stripe-js@"^1.10.0" from @ikas/storefront@4.2.4
npm ERR!     node_modules/@ikas/storefront
npm ERR!       @ikas/storefront@"^4.0.0" from the root project
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^16.8.0 || ^17.0.0 || ^18.0.0" from @stripe/react-stripe-js@1.14.1
npm ERR!     node_modules/@stripe/react-stripe-js
npm ERR!       peer @stripe/react-stripe-js@"^1.10.0" from @ikas/storefront@4.2.4
npm ERR!       node_modules/@ikas/storefront
npm ERR!         @ikas/storefront@"^4.0.0" from the root project
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.2.0
npm ERR!     node_modules/next
npm ERR!       peer next@"12.2.0" from @ikas/storefront@4.2.4
npm ERR!       node_modules/@ikas/storefront
npm ERR!         @ikas/storefront@"^4.0.0" from the root project
npm ERR!   3 more (html-react-parser, mobx-react-lite, next)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from @ikas/storefront@4.2.4
npm ERR! node_modules/@ikas/storefront
npm ERR!   @ikas/storefront@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/apple/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2022-10-30T14_17_16_198Z-debug-0.log

log file: http://jsonblob.com/1036282591606751232

**Comment by dizefurkan** [comment]
Merhaba, hatayı bildirdiğiniz için teşekkür ederiz.  

`npm install --legacy-peer-deps` deneyebilir misiniz?

**Comment by feluna** [comment]
Hello, ikas themes should be used with the **yarn** package manager, as described in the [documentation](http://localhost:4444/docs/theme/getting-started/introduction#creating-your-first-theme). 

It seems we have forgotten to update the instructional commands for create-ikas-theme. We have now changed the instruction commands from npm to yarn. You can run `npx create-ikas-theme@latest` command, and now it will show you all commands with yarn.

If you want to keep using npm, you should either downgrade your npm version, or use the "--legacy-peer-deps" option. However, when you upload your theme, ikas servers will look for a yarn.lock file by default, so its better to use yarn for now, until support for all package managers arrives (pnpm etc).
